name: publish-sponsors
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  generate-sponsors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: "."
